name: balloon_pop_game
description: A cute balloon popping game for Flutter Web.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/sky_background.png
    - assets/images/forest_back.png
    - assets/images/ground_road.png
    - assets/images/nature_assets.png
