name: balloon_pop_game
description: A cute balloon popping game for Flutter Web.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/sky_background.png
    - assets/images/forest_back.png
    - assets/images/ground_road.png
    - assets/images/nature_assets.png
    - assets/images/heart_balloon.png
    - assets/images/mochi_balloon.png
    - assets/images/balloon_star_asset.png
    - assets/images/balloon_flower_asset.png
    - assets/images/balloon_wari_halfmoon_asset.png
    - assets/images/balloon_wari_triangle_asset.png
    - assets/images/balloon_wari_round_asset.png
    - assets/images/balloon_kicks_asset.png
    - assets/images/balloon_boo_asset.png
    - assets/images/balloon_muggy_asset.png
    - assets/images/balloon_gemi_asset.png
    - assets/images/balloon_shushu_asset.png
    - assets/images/gemi_pickaxe_asset.png
    - assets/images/shushu_fork_asset.png
    - assets/images/shushu_cream_wall_asset.png
    - assets/images/shushu_cream_burst_asset.png
    - assets/images/shushu_cream_screen_asset.png
    - assets/images/gemi_background_asset.png
    - assets/images/shushu_background_asset.png
    - assets/images/gemi_background_mobile.png
    - assets/images/shushu_background_mobile.png
    - assets/images/muggy_break.mp3.mp3
    - assets/images/gemi_pickaxe_hit.mp3.mp3
    - assets/images/gemi_break.mp3.mp3
    - assets/images/shushu_fork_hit.mp3.mp3
    - assets/images/shushu_cream_burst.mp3.mp3
    - assets/images/gemi_shard.png.png
    - assets/images/gemi_screen_crack.png.png
    - assets/sounds/mochi_wing_flap.mp3.mp3
    - assets/sounds/wari_watermelon_bite.mp3.mp3
    - assets/sounds/kicks_soccer_kick.mp3.mp3
    - assets/sounds/boo_ghost_woo.mp3.mp3
    - assets/sounds/ui_click.mp3.mp3
    - assets/sounds/boss_appear.mp3.mp3
    - assets/sounds/boss_clear.mp3.mp3
    - assets/sounds/shop_purchase.mp3.mp3
    - assets/sounds/shop_equip.mp3.mp3
